api-key: &api-key
  value: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33643035383838306332653139636365623763336463356538666565303165343662343765626461
    6565363234306135613661653239616436303161323033660a663236353365646630643734383532
    30346537336165636538356432323430323932666262616137356162323461616564613235323037
    6562613834393736660a376163616239613932313038393866633134383261366662633665316132
    39633335316664336430646635353063623161623039656561343338633937306166393138393465
    6335306133396164323733386361316133643436383539323135
taloscluster_a_state: &taloscluster_a_state 'absent'
taloscluster_a_iso: &taloscluster_a_iso 'local:iso/talos-amd64-v1.5.1.iso,media=cdrom'
taloscluster_a_work_mem: &taloscluster_a_work_mem 2048
taloscluster_a_cp_mem: &taloscluster_a_cp_mem 4096
vms: 
  - name: wireguard1
    node: proxmox3
    api_token: *api-key
    id: 300
  - name: kubeinternal1
    node: proxmox2
    api_token: *api-key
    memory: 4096
    cd1: 'nas-iso:iso/ubuntu-22.04.3-live-server-amd64.iso,media=cdrom'
    cpu: 'host'
    id: 302
  - name: loadbalancer3
    node: proxmox3
    api_token: *api-key
    id: 108
  - name: talos-a-cp1
    node: proxmox1
    api_token: *api-key
    memory: *taloscluster_a_cp_mem
    disk1: 'local-lvm:50,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 201
    state: *taloscluster_a_state
  - name: talos-a-cp2
    node: proxmox2
    api_token: *api-key
    memory: *taloscluster_a_cp_mem
    disk1: 'local-lvm:50,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 202
    state: *taloscluster_a_state
  - name: talos-a-cp3
    node: proxmox3
    api_token: *api-key
    memory: *taloscluster_a_cp_mem
    disk1: 'local-lvm:50,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 203
    state: *taloscluster_a_state
  - name: talos-a-w1
    node: proxmox1
    api_token: *api-key
    memory: *taloscluster_a_work_mem
    disk1: 'local-lvm:50,format=raw'
    disk2: 'local-lvm:100,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 211
    state: *taloscluster_a_state
  - name: talos-a-w2
    node: proxmox2
    api_token: *api-key
    memory: *taloscluster_a_work_mem
    disk1: 'local-lvm:50,format=raw'
    disk2: 'local-lvm:100,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 212
    state: *taloscluster_a_state
  - name: talos-a-w3
    node: proxmox3
    api_token: *api-key
    memory: *taloscluster_a_work_mem
    disk1: 'local-lvm:50,format=raw'
    disk2: 'local-lvm:100,format=raw'
    cd1: *taloscluster_a_iso
    cpu: 'host'
    id: 213
    state: *taloscluster_a_state
