haproxy_front_ends:
  - name: fe_ingress_http
    bind: "0.0.0.0:80"
    default_backend: "be_microk8s_http"
  - name: fe_ingress_https
    bind: "0.0.0.0:443"
    log_sni: true
    default_backend: "be_microk8s_https"
    acl:
      - acl_homeassistant req.ssl_sni -i ha.davenull.co.nz
    acl_use_backend:
      - be_homeassistant if acl_homeassistant
    inspectdelay: 10s
  - name: fe_ingress_6443
    bind: "0.0.0.0:6443"
    default_backend: "be_talos-a-cp"
haproxy_back_ends:
  - name: be_microk8s_http
    port: 80
    servers: 
      - "kube04 192.168.1.134"
  - name: be_microk8s_https
    port: 443
    servers: 
      - "kube04 192.168.1.134"
  - name: be_talos-a-cp
    port: 6443
    servers: 
      - "talos-a-cp1 192.168.1.60"
      - "talos-a-cp2 192.168.1.61"
      - "talos-a-cp3 192.168.1.62"
  - name: be_talos-a-workers_http
    port: 80
    servers: 
      - "talos-a-w1 192.168.1.63"
      - "talos-a-w2 192.168.1.64"
      - "talos-a-w3 192.168.1.65"
  - name: be_homeassistant
    port: 443
    servers: 
      - "homeassistant1 192.168.1.173"
haproxy_mode: tcp
keepalived_checks:
    - name: chk_haproxy
      script: "pidof haproxy"
      interval: 2