---
- name: Install desktop packages
  pacman: name={{ item }} state=present
  with_items: "{{ qemu_packages }}"
  become: true

- name: start libvirtd
  service: 
    name: libvirtd
    state: started
    enabled: true
  become: true

- name: Add dave to libvirt group
  debug: 
    msg: TODO Add dave to libvirt group
