#!/usr/bin/env ansible-playbook
---
- hosts: all
  become: true

  tasks:
    - name: Set fsck on boot
      debug:
        msg: TODO - Set fsck on boot

    - name: set correct mirror for pacman
      debug:
        msg: TODO - Set mirror

    - name: update pacman cache
      pacman: 
        update_cache: true

    - name: Install base packages
      pacman: name={{ item }} state=present
      with_items:
        - bind-tools
        - net-tools 
        - rsync 
        - sysstat 
        - atop 
        - openssh 
        - vim 
        - sudo 
        - screen

    - name: Install X packages
      pacman: name={{ item }} state=present
      with_items:
        - xorg-server
        - fluxbox
        - lxdm
        - xf86-video-fbdev

    - name: Start/Enable lxdm
      service: 
        name: lxdm
        enabled: true
        state: started
