---
- name: Install desktop packages
  pacman: name={{ item }} state=present
  with_items: "{{ desktop_packages }}"
  become: true

- name: Install X packages
  pacman: name={{ item }} state=present
  with_items: "{{ x_packages }}"
  become: true

- name: Install AUR packages
  yay: name={{ item }} state=present
  with_items: "{{ aur_packages }}"
  ignore_errors: True

#- name: Install graphics driver  
#  debug: 
#    msg: TODO install correct graphics driver
