---
- name: Install desktop packages
  pacman: name={{ item }} state=present
  with_items: "{{ desktop_packages }}"
  become: true

- name: Install X packages
  pacman: name={{ item }} state=present
  with_items: "{{ x_packages }}"
  become: true

- name: Install build packages
  pacman: 
    name: base-devel 
  become: true

- name: Install AUR packages
  pacaur: name={{ item }} state=present
  with_items: "{{ aur_packages }}"

#- name: Install graphics driver  
#  debug: 
#    msg: TODO install correct graphics driver