---
- name: Install desktop packages
  pacman: name={{ item }} state=present
  with_items: "{{ desktop_packages }}"
  become: true

- name: Install X packages
  pacman: name={{ item }} state=present
  with_items: "{{ x_packages }}"
  become: true

- name: Install build packages
  pacman: 
    name: base-devel 

- name: Install AUR packages
  debug: 
    msg: TODO install AUR package netctltray, clipit, skypeforlinux-bin, pi-bluetooth

- name: Install graphics driver  
  debug: 
    msg: TODO install correct graphics driver