---
# vars file for desktop
desktop_packages:
  - chromium
  - volumeicon
  - gkrellm
  - firefox
  - icedtea-web
  - evince
  - terminator
  - android-tools
  - ansible
  - imagemagick
  - ttf-dejavu
  - pulseaudio
  - vlc
  - dialog
  - xscreensaver
  - redshift
  - python-gobject 
  - python-xdg 
  - librsvg
  - sshfs
  - cbatticon
  - geeqie
  - libreoffice
x_packages:
  - xorg-server
  - fluxbox
  - lxdm
  - xorg-xmodmap
  - xorg-xev
  - xorg-xbacklight
