---
- name: Install keepalived
  package: 
    name: keepalived
    state: present

- name: Create keepalived config from template 
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0600
  notify: "restart keepalived"

- name: Start and Enable keepalived
  service:
    name: keepalived
    state: started
    enabled: yes