---
- name: Install Docker
  pacman: name={{ docker_packages }} state=present
  
  become: true

- name: Add dave to docker group
  debug: 
    msg: TODO Add dave to docker group

- name: Start/Enable docker daemon
  service: 
    name: docker
    enabled: true
    state: started
  become: true
