---
- name: Set timezone
  file:
    state: link
    src: /usr/share/zoneinfo/Pacific/Auckland
    path: /etc/localtime
    force: true
  become: true

- name: Generate NZ locale
  locale_gen:
    name: en_NZ.UTF-8
  become: true

- name: Copy locale.conf across
  copy:
    dest: /etc/locale.conf
    content: "LANG=en_NZ.UTF-8\n"
    mode: 644
    owner: root
    group: root
  become: true

- name: Copy chrony.conf in
  copy: 
    dest: /etc/chrony.conf
    src: roles/base/files/chrony.conf
    mode: 644
    owner: root
    group: root
  become: true
  notify:
  - restart chrony
