---
- name: Created build dir
  file:
    path: /home/dave/git/pkgbuild
    state: directory
    mode: 0755

- name: check cower authors gpg key
  shell: gpg --list-keys | grep 1EB2638FF56C0C53 &> /dev/null
  register: result
  ignore_errors: True

- name: import cower authors gpg key
  shell: gpg --recv-keys 1EB2638FF56C0C53
  when: result is failed

- name: Clone down cower package build
  shell: git clone https://aur.archlinux.org/cower.git
  args:  
    creates: /home/dave/git/pkgbuild/cower
    chdir: /home/dave/git/pkgbuild

- name: check cower install
  shell: pacman -Q cower &> /dev/null
  register: result
  ignore_errors: True

- name: Clone down auracle-git package build
  shell: git clone https://aur.archlinux.org/auracle-git.git
  args:  
    creates: /home/dave/git/pkgbuild/auracle-git
    chdir: /home/dave/git/pkgbuild

- name: check auracle-git install
  shell: pacman -Q auracle-git &> /dev/null
  register: result
  ignore_errors: True

- name: Build/Install auracle-git
  shell: makepkg -siA --noconfirm
  args:
    chdir: /home/dave/git/pkgbuild/auracle-git
    executable: /bin/bash
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  when: result is failed

- name: Clone down pacaur package build
  shell: git clone https://aur.archlinux.org/pacaur.git
  args:  
    creates: /home/dave/git/pkgbuild/pacaur
    chdir: /home/dave/git/pkgbuild

- name: check pacaur install
  shell: pacman -Q pacaur &> /dev/null
  register: result
  ignore_errors: True

- name: Build/Install pacaur
  shell: makepkg -siA --noconfirm
  args:
    chdir: /home/dave/git/pkgbuild/pacaur
    executable: /bin/bash
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  when: result is failed