---
- name: USB permissions for udev
  copy: 
    src='files/weather.rules' 
    dest='/etc/udev/rules.d/weather.rules' 
    owner='root' 
    group='root'
  become: true

- name: systemd initscript for weewx
  copy: 
    src='files/weewx.service' 
    dest='/etc/systemd/system/weewx.service' 
    owner='root' 
    group='root'
  become: true
  register: initscript

- name: systemd reload
  shell: 'systemctl daemon-reload'
  become: true
  when: initscript.changed

- name: enable weewx on boot
  service: name='weewx' enabled='true'
  become: true